/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.esspi.hcbptool;

import com.esspi.hcbptool.ui.AddDBPaneController;
import com.esspi.hcbptool.ui.MainMenuBarController;
import com.esspi.hcbptool.ui.SetDBPanelController;
import com.esspi.hcbptool.ui.SystemTrayController;
import com.esspi.hcbptool.ui.TransferPanelController;
import java.util.List;
import javax.swing.ImageIcon;
import lombok.Data;
import lombok.Getter;

/**
 *
 * @author presmelito.villanuev
 */
@Data
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private List<String> selectedFolders;
    @Getter
    private static MainFrame instance;

    public MainFrame() {
        instance = this;
        initComponents();
        MainMenuBarController.getInstance().init();
        TransferPanelController.getInstance().initTransferPanel();
        SystemTrayController.getInstance().initSystemTray();
        AddDBPaneController.getInstance().init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        tranPanel = new javax.swing.JPanel();
        toRepoBtn = new javax.swing.JButton();
        toWorkspaceBtn = new javax.swing.JButton();
        tranDeSelectAllBtn = new javax.swing.JButton();
        tranSelectAllBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foldersPanel = new javax.swing.JPanel();
        repoPathTf = new javax.swing.JLabel();
        workspacePathTf = new javax.swing.JLabel();
        setDbPanel = new javax.swing.JPanel();
        setBtnSDB = new javax.swing.JButton();
        removeBtnSDB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        dbConfigTable = new javax.swing.JTable();
        statusLabelSDB = new javax.swing.JLabel();
        addDbPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameFieldADB = new javax.swing.JTextField();
        dbNameFieldADB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminIdFieldADB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminPassFieldADB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userIdFieldADB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        userPassFieldADB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hostFieldADB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        portFieldADB = new javax.swing.JTextField();
        addBtnADB = new javax.swing.JButton();
        testBtnADB = new javax.swing.JButton();
        MainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        changeMenu = new javax.swing.JMenu();
        changeRepoPathMenuItem = new javax.swing.JMenuItem();
        changeWorkspacePathMenuItem = new javax.swing.JMenuItem();
        saveConfigMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItemBtn = new javax.swing.JMenuItem();

        setTitle("Hc Bp Tool");
        setForeground(java.awt.Color.lightGray);
        setIconImage(new ImageIcon(Hcbptool.class.getClassLoader().getResource("presico.png")).getImage());
        setResizable(false);

        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        toRepoBtn.setText("To Repository");

        toWorkspaceBtn.setText("To Workspace");

        tranDeSelectAllBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tranDeSelectAllBtn.setText("Deselect All");

        tranSelectAllBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tranSelectAllBtn.setText("Select All");

        foldersPanel.setLayout(new javax.swing.BoxLayout(foldersPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(foldersPanel);

        repoPathTf.setText("Repository :");

        workspacePathTf.setText("Workspace :");

        javax.swing.GroupLayout tranPanelLayout = new javax.swing.GroupLayout(tranPanel);
        tranPanel.setLayout(tranPanelLayout);
        tranPanelLayout.setHorizontalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tranPanelLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(toWorkspaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tranSelectAllBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tranDeSelectAllBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tranPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addComponent(repoPathTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workspacePathTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tranPanelLayout.createSequentialGroup()
                            .addComponent(toRepoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 376, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        tranPanelLayout.setVerticalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tranPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tranSelectAllBtn)
                    .addComponent(tranDeSelectAllBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(toWorkspaceBtn)
                .addContainerGap())
            .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tranPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(repoPathTf)
                    .addGap(11, 11, 11)
                    .addComponent(workspacePathTf)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(toRepoBtn)
                    .addContainerGap()))
        );

        jTabbedPane.addTab("Tran", tranPanel);

        setBtnSDB.setText("Set");

        removeBtnSDB.setText("Remove");

        dbConfigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Host", "Port", "Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dbConfigTable.setRowHeight(30);
        dbConfigTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(dbConfigTable);
        if (dbConfigTable.getColumnModel().getColumnCount() > 0) {
            dbConfigTable.getColumnModel().getColumn(0).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(1).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(2).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout setDbPanelLayout = new javax.swing.GroupLayout(setDbPanel);
        setDbPanel.setLayout(setDbPanelLayout);
        setDbPanelLayout.setHorizontalGroup(
            setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setDbPanelLayout.createSequentialGroup()
                        .addComponent(statusLabelSDB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setDbPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removeBtnSDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setBtnSDB)))
                .addContainerGap())
        );
        setDbPanelLayout.setVerticalGroup(
            setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabelSDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setBtnSDB)
                    .addComponent(removeBtnSDB))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Set DB", setDbPanel);

        jLabel1.setText("Name");

        jLabel4.setText("Db Name");

        jLabel2.setText("Admin Id");

        jLabel5.setText("Password");

        jLabel3.setText("User Id");

        jLabel6.setText("Password");

        jLabel7.setText("Host");

        jLabel8.setText("Port");

        addBtnADB.setText("Add");

        testBtnADB.setText("Test");

        javax.swing.GroupLayout addDbPanelLayout = new javax.swing.GroupLayout(addDbPanel);
        addDbPanel.setLayout(addDbPanelLayout);
        addDbPanelLayout.setHorizontalGroup(
            addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDbPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hostFieldADB, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(userIdFieldADB))
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDbPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(testBtnADB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtnADB))
                    .addGroup(addDbPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbNameFieldADB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminPassFieldADB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userPassFieldADB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(portFieldADB))))
                .addContainerGap())
            .addGroup(addDbPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminIdFieldADB, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(nameFieldADB))
                .addGap(306, 306, 306))
        );
        addDbPanelLayout.setVerticalGroup(
            addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDbPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(dbNameFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminIdFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(adminPassFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userIdFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(userPassFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hostFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(portFieldADB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(addDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtnADB)
                    .addComponent(testBtnADB))
                .addContainerGap())
        );

        jTabbedPane.addTab("Add DB", addDbPanel);

        fileMenu.setText("File");

        changeMenu.setText("Change Path");

        changeRepoPathMenuItem.setText("Repository");
        changeMenu.add(changeRepoPathMenuItem);

        changeWorkspacePathMenuItem.setText("Workspace");
        changeMenu.add(changeWorkspacePathMenuItem);

        fileMenu.add(changeMenu);

        saveConfigMenuItem.setText("Save Config");
        fileMenu.add(saveConfigMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItemBtn.setText("Exit");
        fileMenu.add(exitMenuItemBtn);

        MainMenuBar.add(fileMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        if (jTabbedPane.getSelectedIndex() == 1) {
            SetDBPanelController.getInstance().buildSetDbPanel();
        }
    }//GEN-LAST:event_jTabbedPaneStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JButton addBtnADB;
    private javax.swing.JPanel addDbPanel;
    private javax.swing.JTextField adminIdFieldADB;
    private javax.swing.JTextField adminPassFieldADB;
    private javax.swing.JMenu changeMenu;
    private javax.swing.JMenuItem changeRepoPathMenuItem;
    private javax.swing.JMenuItem changeWorkspacePathMenuItem;
    private javax.swing.JTable dbConfigTable;
    private javax.swing.JTextField dbNameFieldADB;
    private javax.swing.JMenuItem exitMenuItemBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel foldersPanel;
    private javax.swing.JTextField hostFieldADB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField nameFieldADB;
    private javax.swing.JTextField portFieldADB;
    private javax.swing.JButton removeBtnSDB;
    private javax.swing.JLabel repoPathTf;
    private javax.swing.JMenuItem saveConfigMenuItem;
    private javax.swing.JButton setBtnSDB;
    private javax.swing.JPanel setDbPanel;
    private javax.swing.JLabel statusLabelSDB;
    private javax.swing.JButton testBtnADB;
    private javax.swing.JButton toRepoBtn;
    private javax.swing.JButton toWorkspaceBtn;
    private javax.swing.JButton tranDeSelectAllBtn;
    private javax.swing.JPanel tranPanel;
    private javax.swing.JButton tranSelectAllBtn;
    private javax.swing.JTextField userIdFieldADB;
    private javax.swing.JTextField userPassFieldADB;
    private javax.swing.JLabel workspacePathTf;
    // End of variables declaration//GEN-END:variables

}
