/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.esspi.hcbptool;

import com.esspi.hcbptool.ui.AddDBPaneController;
import com.esspi.hcbptool.ui.GITPanelUIManager;
import com.esspi.hcbptool.ui.MainMenuBarController;
import com.esspi.hcbptool.ui.SetDBPanelController;
import com.esspi.hcbptool.ui.SystemTrayController;
import com.esspi.hcbptool.ui.TransferPanelController;
import com.esspi.hcbptool.ui.UIManagerInitiator;
import java.util.List;
import javax.swing.ImageIcon;
import lombok.Getter;
import lombok.Data;

/**
 *
 * @author presmelito.villanuev
 */
@Data
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private List<String> selectedFolders;
    
    @Getter
    private static MainFrame instance;

    public MainFrame() {
        instance = this;
        UIManagerInitiator.getInstance().init();
        initComponents();
        MainMenuBarController.getInstance().init();
        TransferPanelController.getInstance().initTransferPanel();
        SystemTrayController.getInstance().initSystemTray();
        AddDBPaneController.getInstance().init();
        GITPanelUIManager.getInstance().init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gitTabbedPane = new javax.swing.JTabbedPane();
        tranPanel = new javax.swing.JPanel();
        toRepoBtn = new javax.swing.JButton();
        toWorkspaceBtn = new javax.swing.JButton();
        tranDeSelectAllBtn = new javax.swing.JButton();
        tranSelectAllBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foldersPanel = new javax.swing.JPanel();
        repoPathTf = new javax.swing.JLabel();
        workspacePathTf = new javax.swing.JLabel();
        setDbPanel = new javax.swing.JPanel();
        setBtnSDB = new javax.swing.JButton();
        removeBtnSDB = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        dbConfigTable = new javax.swing.JTable();
        statusLabelSDB = new javax.swing.JLabel();
        addDbPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameFieldADB = new javax.swing.JTextField();
        dbNameFieldADB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminIdFieldADB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        adminPassFieldADB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userIdFieldADB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        userPassFieldADB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hostFieldADB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        portFieldADB = new javax.swing.JTextField();
        addBtnADB = new javax.swing.JButton();
        testBtnADB = new javax.swing.JButton();
        gitPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gitFileStagedList = new javax.swing.JList<com.esspi.hcbptool.git.GitFile>();
        jScrollPane4 = new javax.swing.JScrollPane();
        gitFileUnstagedList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        gitDiffTextPane = new javax.swing.JTextPane();
        MainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        changeMenu = new javax.swing.JMenu();
        changeRepoPathMenuItem = new javax.swing.JMenuItem();
        changeWorkspacePathMenuItem = new javax.swing.JMenuItem();
        saveConfigMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItemBtn = new javax.swing.JMenuItem();
        themeMenu = new javax.swing.JMenu();
        lightThemeMenuItem = new javax.swing.JMenuItem();
        darkThemeMenuItem = new javax.swing.JMenuItem();

        setTitle("Hc Bp Tool");
        setForeground(java.awt.Color.lightGray);
        setIconImage(new ImageIcon(Hcbptool.class.getClassLoader().getResource("presico.png")).getImage());
        setResizable(false);

        gitTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gitTabbedPaneStateChanged(evt);
            }
        });

        toRepoBtn.setText("To Repository");

        toWorkspaceBtn.setText("To Workspace");

        tranDeSelectAllBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tranDeSelectAllBtn.setMaximumSize(new java.awt.Dimension(21, 21));
        tranDeSelectAllBtn.setMinimumSize(new java.awt.Dimension(21, 21));
        tranDeSelectAllBtn.setName(""); // NOI18N
        tranDeSelectAllBtn.setPreferredSize(new java.awt.Dimension(21, 21));

        tranSelectAllBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tranSelectAllBtn.setMaximumSize(new java.awt.Dimension(21, 21));
        tranSelectAllBtn.setMinimumSize(new java.awt.Dimension(21, 21));
        tranSelectAllBtn.setPreferredSize(new java.awt.Dimension(21, 21));

        foldersPanel.setLayout(new javax.swing.BoxLayout(foldersPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(foldersPanel);

        repoPathTf.setText("Repository :");

        workspacePathTf.setText("Workspace :");

        javax.swing.GroupLayout tranPanelLayout = new javax.swing.GroupLayout(tranPanel);
        tranPanel.setLayout(tranPanelLayout);
        tranPanelLayout.setHorizontalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tranPanelLayout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addComponent(toWorkspaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tranSelectAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tranDeSelectAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tranPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addComponent(repoPathTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workspacePathTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tranPanelLayout.createSequentialGroup()
                            .addComponent(toRepoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 580, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        tranPanelLayout.setVerticalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tranPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tranSelectAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tranDeSelectAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(toWorkspaceBtn)
                .addContainerGap())
            .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tranPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(repoPathTf)
                    .addGap(11, 11, 11)
                    .addComponent(workspacePathTf)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(toRepoBtn)
                    .addContainerGap()))
        );

        gitTabbedPane.addTab("Transfer", tranPanel);

        setBtnSDB.setText("Set");

        removeBtnSDB.setText("Remove");

        dbConfigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Host", "Port", "Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dbConfigTable.setRowHeight(30);
        dbConfigTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(dbConfigTable);
        if (dbConfigTable.getColumnModel().getColumnCount() > 0) {
            dbConfigTable.getColumnModel().getColumn(0).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(1).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(2).setResizable(false);
            dbConfigTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout setDbPanelLayout = new javax.swing.GroupLayout(setDbPanel);
        setDbPanel.setLayout(setDbPanelLayout);
        setDbPanelLayout.setHorizontalGroup(
            setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setDbPanelLayout.createSequentialGroup()
                        .addComponent(statusLabelSDB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setDbPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removeBtnSDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setBtnSDB)))
                .addContainerGap())
        );
        setDbPanelLayout.setVerticalGroup(
            setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabelSDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setBtnSDB)
                    .addComponent(removeBtnSDB))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        gitTabbedPane.addTab("Set DB", setDbPanel);

        addDbPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(nameFieldADB, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(dbNameFieldADB, gridBagConstraints);

        jLabel4.setText("Db Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel4, gridBagConstraints);

        jLabel2.setText("Admin Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(adminIdFieldADB, gridBagConstraints);

        jLabel5.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(adminPassFieldADB, gridBagConstraints);

        jLabel3.setText("User Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(userIdFieldADB, gridBagConstraints);

        jLabel6.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(userPassFieldADB, gridBagConstraints);

        jLabel7.setText("Host");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(hostFieldADB, gridBagConstraints);

        jLabel8.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(portFieldADB, gridBagConstraints);

        addBtnADB.setText("Add");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(addBtnADB, gridBagConstraints);

        testBtnADB.setText("Test");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        addDbPanel.add(testBtnADB, gridBagConstraints);

        gitTabbedPane.addTab("Add DB", addDbPanel);

        gitPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setViewportView(gitFileStagedList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gitPanel.add(jScrollPane2, gridBagConstraints);

        jScrollPane4.setViewportView(gitFileUnstagedList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gitPanel.add(jScrollPane4, gridBagConstraints);

        gitDiffTextPane.setEditable(false);
        jScrollPane5.setViewportView(gitDiffTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gitPanel.add(jScrollPane5, gridBagConstraints);

        gitTabbedPane.addTab("GIT", gitPanel);

        fileMenu.setText("File");

        changeMenu.setText("Change Path");

        changeRepoPathMenuItem.setText("Repository");
        changeMenu.add(changeRepoPathMenuItem);

        changeWorkspacePathMenuItem.setText("Workspace");
        changeMenu.add(changeWorkspacePathMenuItem);

        fileMenu.add(changeMenu);

        saveConfigMenuItem.setText("Save Config");
        fileMenu.add(saveConfigMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItemBtn.setText("Exit");
        fileMenu.add(exitMenuItemBtn);

        MainMenuBar.add(fileMenu);

        themeMenu.setText("Theme");

        lightThemeMenuItem.setText("Light");
        themeMenu.add(lightThemeMenuItem);

        darkThemeMenuItem.setText("Dark");
        themeMenu.add(darkThemeMenuItem);

        MainMenuBar.add(themeMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gitTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gitTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void gitTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gitTabbedPaneStateChanged
        if (gitTabbedPane.getSelectedIndex() == 1) {
            SetDBPanelController.getInstance().buildSetDbPanel();
        }
    }//GEN-LAST:event_gitTabbedPaneStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JButton addBtnADB;
    private javax.swing.JPanel addDbPanel;
    private javax.swing.JTextField adminIdFieldADB;
    private javax.swing.JTextField adminPassFieldADB;
    private javax.swing.JMenu changeMenu;
    private javax.swing.JMenuItem changeRepoPathMenuItem;
    private javax.swing.JMenuItem changeWorkspacePathMenuItem;
    private javax.swing.JMenuItem darkThemeMenuItem;
    private javax.swing.JTable dbConfigTable;
    private javax.swing.JTextField dbNameFieldADB;
    private javax.swing.JMenuItem exitMenuItemBtn;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel foldersPanel;
    private javax.swing.JTextPane gitDiffTextPane;
    private javax.swing.JList<com.esspi.hcbptool.git.GitFile> gitFileStagedList;
    private javax.swing.JList<com.esspi.hcbptool.git.GitFile> gitFileUnstagedList;
    private javax.swing.JPanel gitPanel;
    private javax.swing.JTabbedPane gitTabbedPane;
    private javax.swing.JTextField hostFieldADB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem lightThemeMenuItem;
    private javax.swing.JTextField nameFieldADB;
    private javax.swing.JTextField portFieldADB;
    private javax.swing.JButton removeBtnSDB;
    private javax.swing.JLabel repoPathTf;
    private javax.swing.JMenuItem saveConfigMenuItem;
    private javax.swing.JButton setBtnSDB;
    private javax.swing.JPanel setDbPanel;
    private javax.swing.JLabel statusLabelSDB;
    private javax.swing.JButton testBtnADB;
    private javax.swing.JMenu themeMenu;
    private javax.swing.JButton toRepoBtn;
    private javax.swing.JButton toWorkspaceBtn;
    private javax.swing.JButton tranDeSelectAllBtn;
    private javax.swing.JPanel tranPanel;
    private javax.swing.JButton tranSelectAllBtn;
    private javax.swing.JTextField userIdFieldADB;
    private javax.swing.JTextField userPassFieldADB;
    private javax.swing.JLabel workspacePathTf;
    // End of variables declaration//GEN-END:variables

}
